### ISSUE TITLE
Why "complex" Union type for content relationship field while it could simply be a Maybe (Value | null)?

### ISSUE THREAD

**Issue by maapteh** [prismicio/prismic-types#50] opened 2022-10-05 18:16 UTC
When im using the auto generated types i noticed for example:

```
const relatedFaq: EmptyLinkField<"Document"> | FilledContentRelationshipField<"faq", string, never>
```

where the emptyLinkField is not much like:

```
{ link_type: 'Document' }
```

my question is why you don't just pass null in that case? It makes it also way easier to consume down the line with if else. An empty document is not adding any value

**Comment by lihbr** [comment] 2022-10-05 18:38
Hey @maapteh, thanks for your question!

Types from `@prismicio/types` describe data yielded by Prismic API v2. Within this API, a content relationship field can be one of two states: empty or filled.

- An empty content relationship field is represented by the first part of the type, `EmptyLinkField<"Document">`;
- A filled content relationship field is described by the latter, `FilledContentRelationshipField<"faq", string, never>`.

In an ideal world, it could make sense for an empty field to be just `null`. The reason it's kept as an object is for various legacy and compatibility reasons, mainly that having an object was more permissive and prevented errors such as `Cannot read properties of null (reading 'url')`.

Checking for a field to be empty or filled is a common pattern though, to achieve that, the best and battle-tested method to check for a field's state is by using `@prismicio/helpers` `isFilled` methods. These methods even come with great type narrowing.

```typescript
import { isFilled } from "@prismicio/helpers";

/* ... */

if (isFilled.contentRelationship(doc.data.relatedFaq)) {
  /* ... */
}
```

Let us know if that answers your question :)

**Comment by maapteh** [comment] 2022-10-05 20:46
Well funny enough your helper is even casting it wrong, there it suddenly results not in a Maybe, but always a response

<img width="636" alt="Screenshot 2022-10-05 at 22 40 07" src="https://user-images.githubusercontent.com/25961356/194159240-1b7d0eb4-56b6-420b-8da2-38a4f5f5e2f6.png">

So when not adding any content for this block, TS will trip and block my whole page at ln8

```
    const faqContent = prismicH.isFilled.contentRelationship(relatedFaq)
      ? relatedFaq
      : null;

    // still issue at https://github.com/microsoft/TypeScript/issues/40330
    const [relatedFaqDocument] = await Promise.all([
      // THIS IS WRONG, TS SHOULD HELP ME WITH SAYING faqContent is nullable and faqContent?.id should be used
      ...(faqContent.id
        ? [client.getByID<FaqDocument>((relatedFaq as any).id)]
        : [null]),
    ]);
```

To be honest instead of empty making it just a dumb object is not adding any value, nullable objects are just to prevent stuff and tell you explicitly when to use `foo?.`. Now you add complexity to the consumer side. 

I hope in a V2 or V3 you will not think too much about the past, thats why software like atlassian is so shitty to build your api's upon. Nullable when not found is perfect, because `{ link_type: 'Document' }` is NOT really helpful. My typings see only that field now as the field which is there so i cant even do a check but have to write a special guard for it!! The helper is not a guard. So no unfortunately this doesn't really help :(

**Comment by maapteh** [comment] 2022-10-05 20:51
btw the helpers are also not tree shakable, whole objects ... :)

**Comment by lihbr** [comment] 2022-10-06 07:43
> Good evening Lucie, Well funny enough your helper is even casting it wrong, there it suddenly results not in a Maybe, but always a response

Unfortunately, I'm not able to reproduce it, [see my setup here](https://github.com/prismicio/prismic-types/files/9722090/types-50-1.zip), type narrows as expected.

![image](https://user-images.githubusercontent.com/25330882/194239215-8b17e7e1-5c06-4e60-a802-f1999f9163ec.png)

Happy to troubleshoot that further, if you'd like to too, I'll need more information about your setup and a minimal reproduction.

> To be honest instead of empty making it just a dumb object is not adding any value, nullable objects are just to prevent stuff and tell you explicitly when to use foo?.. Now you add complexity to the consumer side.
>
> I hope in a V2 or V3 you will not think too much about the past, thats why software like atlassian is so shitty to build your api's upon. Nullable when not found is perfect, because { link_type: 'Document' } is NOT really helpful. [...] (trusting the types and get runtime error when not filled in) :(

We agree with you, I'll forward that feedback to our product team.

> btw the helpers are also not tree shakable, whole objects ... :)

Indeed, we've been working on improving our tree shakability recently as we have greater issues with it. For now I'm afraid that'll be an extra 350 bytes in the bundle.

**Comment by lihbr** [comment] 2022-10-09 08:46
I'm still not able to reproduce, see my updated setup: [types-50-2.zip](https://github.com/prismicio/prismic-types/files/9741109/types-50-2.zip)

> ```
> const { relation, ...here we take many more since we will all put them in next chain } = sink.data
> 
> const relBug = prismicH.isFilled.contentRelationship(relation)
> ```
> 
> now relBug is suddenly not optional :)

Indeed, `isFilled*` methods return a boolean representing the field's state, not the field itself.

---

Unless you provide a comprehensive reproduction I'll close this issue.

**Comment by lihbr** [comment] 2022-12-08 17:00
Closing as the thread has become stale, happy to reopen it if you'd like to continue troubleshooting the above together~

**Closed by lihbr** 2022-12-08 17:00 UTC
Labels: question, need repro

**Comment by esbeto** [comment] 2022-12-17 00:16
Hi, I arrived here by searching for the function I was using `isFilled.contentRelationship`, and typescript doesn't seem to understand that the value is filled.

I'm using:
```
   "@prismicio/types": "^0.2.4",
    "prismic-ts-codegen": "^0.1.5",
```

Here's my code:
```
import { isFilled } from "@prismicio/helpers";
import { BlogArticleDocument, BlogCategoryDocument } from "~~/types.generated";

function getCategoryLabel(article: BlogArticleDocument) {
  const category = article.data.blog_category;
  const blogCategory = isFilled.contentRelationship(category) ? category : null;

  if (blogCategory) {
    return blogCategory.data.label;
  }

  return "";
}
```

But I'm getting the following type error:
```
'blogCategory.data' is of type 'unknown'.ts(18046)
```

<img width="923" alt="Screenshot 2022-12-17 at 01 15 12" src="https://user-images.githubusercontent.com/1455236/208212051-38d9ae81-f62e-4aca-95c8-89c50dea292d.png">

I'm not sure how to get the category label field. Can you help me?

**Comment by esbeto** [comment] 2022-12-17 00:35
OK, I just fixed it, I looked at the documentation, specifically the last example here:
https://prismic.io/docs/technical-reference/prismicio-client#typescript

Just for reference, this was the code that pleased Typescript:
```
import { isFilled } from "@prismicio/helpers";
import { BlogArticleDocument, BlogCategoryDocument } from "~~/types.generated";

function getCategoryLabel(article: BlogArticleDocument) {
  const category = article.data.blog_category as typeof article.data.blog_category & {
    data: Pick<BlogCategoryDocument['data'], "label">
  }

  const blogCategory = isFilled.contentRelationship(category) ? category : null;

  if (blogCategory) {
    return blogCategory.data.label;
  }

  return "";
}
```

**Comment by lihbr** [comment] 2022-12-20 10:14
Hey @esbeto, thanks for sharing your findings!

Indeed, the API is not really convenient to use when it comes to content relationship fetchLinks/graphQuery usage. The above you shared is the current recommended way of dealing with it.

We'll try to explore if a better API can be made available :)
